version: "3.8"

services:
   db:
    image: postgres:16.1-bookworm
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      -  "${DB_PORT}:5432"
    volumes:
      - ${DB_SQL_STORAGE}:/var/lib/postgresql/data

