"""Added account table

Revision ID: ce828b7f1423
Revises: 
Create Date: 2024-03-04 12:40:12.760300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce828b7f1423'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Accountname', sa.String(), nullable=True),
    sa.Column('accountTag', sa.String(), nullable=True),
    sa.Column('eloWhenOrdered', sa.String(), nullable=True),
    sa.Column('usernameLogin', sa.String(), nullable=True),
    sa.Column('passwordLogin', sa.String(), nullable=True),
    sa.Column('idBooster', sa.Integer(), nullable=True),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idBooster'], ['booster.id'], ),
    sa.ForeignKeyConstraint(['idCliente'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('booster')
    # ### end Alembic commands ###
