version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: dockerfiles/api.dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:16.1-bookworm
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      -  "${DB_PORT}:5432"
    volumes:
      - ${DB_SQL_STORAGE}:/var/lib/postgresql/data

volumes:
  db-data: 
